from tkinter import *
from tkinter import ttk
import serial.tools.list_ports
from time import sleep
 
 
main = Tk()
main.title('                                                                                                    Universal Phone Tool 1.0.0 Beta')
main.resizable(width=False, height=False)


screen_x = int(main.winfo_screenwidth())
screen_y = int(main.winfo_screenheight())
window_y = 600
window_x = 850

posX = (screen_x//2) - (window_x//2)
posY = (screen_y//2) - (window_y//2)

geo = "{}x{}+{}+{}".format(window_x,window_y,posX,posY)
main.geometry(geo)

 
# gives weight to the cells in the grid
rows = 0
while rows < 50:
    main.rowconfigure(rows, weight=1)
    main.columnconfigure(rows, weight=1)
    rows += 1
 
# Defines and places the notebook widget
nb = ttk.Notebook(main)
nb.grid(row=1, column=0, columnspan=10, rowspan=30,sticky='NESW')
 
# Adds tab 1 of the notebook
page1 = ttk.Frame(nb)
nb.add(page1, text='Samsung')
Radio_frp= ttk.Radiobutton(page1,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page1,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page1,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page1,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page1,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page1,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page1,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page1,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page1,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page1,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page1,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page1,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page1,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page1,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page1,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page1,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page1,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page1,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page1,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page1,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page1,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page1,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page1,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page1,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)


# Adds tab 2 of the notebook
page2 = ttk.Frame(nb)
nb.add(page2, text='iPhoneSPD')
Radio_frp= ttk.Radiobutton(page2,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page2,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page2,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page2,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page2,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page2,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page2,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page2,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page2,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page2,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page2,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page2,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page2,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page2,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page2,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page2,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page2,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page2,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page2,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page2,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page2,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page2,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page2,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page2,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page3 = ttk.Frame(nb)
nb.add(page3, text='Huawei')
Radio_frp= ttk.Radiobutton(page3,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page3,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page3,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page3,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page3,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page3,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page3,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page3,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page3,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page3,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page3,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page3,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page3,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page3,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page3,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page3,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page3,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page3,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page3,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page3,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page3,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page3,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page3,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page3,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page4 = ttk.Frame(nb)
nb.add(page4, text='Oppo')
Radio_frp= ttk.Radiobutton(page4,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page4,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page4,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page4,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page4,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page4,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page4,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page4,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page4,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page4,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page4,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page4,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page4,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page4,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page4,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page4,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page4,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page4,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page4,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page4,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page4,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page4,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page4,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page4,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page5 = ttk.Frame(nb)
nb.add(page5, text='Mediatek')
Radio_frp= ttk.Radiobutton(page5,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page5,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page5,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page5,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page5,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page5,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page5,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page5,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page5,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page5,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page5,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page5,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page5,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page5,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page5,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page5,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page5,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page5,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page5,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page5,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page5,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page5,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page5,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page5,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page6 = ttk.Frame(nb)
nb.add(page6, text='Spreadtrum')
Radio_frp= ttk.Radiobutton(page6,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page6,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page6,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page6,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page6,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page6,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page6,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page6,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page6,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page6,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page6,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page6,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page6,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page6,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page6,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page6,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page6,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page6,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page6,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page6,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page6,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page6,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page6,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page6,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page7 = ttk.Frame(nb)
nb.add(page7, text='LG')
Radio_frp= ttk.Radiobutton(page7,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page7,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page7,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page7,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page7,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page7,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page7,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page7,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page7,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page7,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page7,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page7,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page7,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page7,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page7,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page7,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page7,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page7,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page7,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page7,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page7,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page7,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page7,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page7,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page8 = ttk.Frame(nb)
nb.add(page8, text='Motorola')
Radio_frp= ttk.Radiobutton(page8,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page8,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page8,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page8,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page8,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page8,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page8,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page8,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page8,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page8,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page8,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page8,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page8,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page8,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page8,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page8,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page8,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page8,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page8,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page8,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page8,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page8,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page8,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page8,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page9 = ttk.Frame(nb)
nb.add(page9, text='Xiaomi')
Radio_frp= ttk.Radiobutton(page9,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page9,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page9,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page9,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page9,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page9,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page9,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page9,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page9,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page9,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page9,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page9,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page9,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page9,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page9,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page9,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page9,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page9,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page9,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page9,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page9,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page9,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page9,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page9,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page10 = ttk.Frame(nb)
nb.add(page10, text='HTC')
Radio_frp= ttk.Radiobutton(page10,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page10,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page10,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page10,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page10,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page10,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page10,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page10,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page10,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page10,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page10,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page10,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page10,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page10,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page10,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page10,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page10,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page10,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page10,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page10,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page10,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page10,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page10,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page10,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page11 = ttk.Frame(nb)
nb.add(page11, text='FRP')
Radio_frp= ttk.Radiobutton(page11,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page11,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page11,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page11,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page11,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page11,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page11,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page11,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page11,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page11,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page11,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page11,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page11,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page11,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page11,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page11,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page11,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page11,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page11,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page11,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page11,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page11,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page11,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page11,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page12 = ttk.Frame(nb)
nb.add(page12, text='QUALCOMM')
Radio_frp= ttk.Radiobutton(page12,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page12,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page12,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page12,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page12,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page12,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page12,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page12,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page12,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page12,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page12,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page12,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page12,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page12,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page12,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page12,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page12,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page12,text='Reboot to edl Mode',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page12,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page12,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page12,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page12,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page12,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page12,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page13 = ttk.Frame(nb)
nb.add(page13, text='NOKIA')
Radio_frp= ttk.Radiobutton(page13,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page13,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page13,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page13,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page13,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page13,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page13,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page13,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page13,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page13,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page13,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page13,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page13,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page13,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page13,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page13,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page13,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page13,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page13,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page13,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page13,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page13,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page13,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page13,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page14 = ttk.Frame(nb)
nb.add(page14, text='ASUS')
Radio_frp= ttk.Radiobutton(page14,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page14,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page14,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page14,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page14,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page14,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page14,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page14,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page14,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page14,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page14,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page14,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page14,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page14,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page14,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page14,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page14,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page14,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page14,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page14,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radio_sprint = ttk.Radiobutton(page14,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page14,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page14,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page14,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

page15 = ttk.Frame(nb)
nb.add(page15, text='VIVO')
Radio_frp= ttk.Radiobutton(page15,text='Reset Frp',value=0)
Radio_frp.grid(row=2,column=0)
Radio_write= ttk.Radiobutton(page15,text='Write Flash',value=1)
Radio_write.grid(row=2,column=1)
Radio_direct_unlock= ttk.Radiobutton(page15,text='Direct Unlock',value=2)
Radio_direct_unlock.grid(row=2,column=2) 
Radio_read_pit= ttk.Radiobutton(page15,text='Read Pit',value=3)
Radio_read_pit.grid(row=2,column=3)
Radio_arabic = ttk.Radiobutton(page15,text='Add Arabic (8.0)(7.0)(6.0)',value=4)
Radio_arabic.grid(row=2,column=4)
Radio_repairimei = ttk.Radiobutton(page15,text='Repair IMEI ',value=5)
Radio_repairimei.grid(row=2,column=5)
Radio_readinfo= ttk.Radiobutton(page15,text='Readinfo',value=6)
Radio_readinfo.grid(row=3,column=0)
Radio_writecert= ttk.Radiobutton(page15,text='Write Cert',value=7)
Radio_writecert.grid(row=3,column=1)
Radio_readpattern= ttk.Radiobutton(page15,text='Read Pattern',value=8)
Radio_readpattern.grid(row=3,column=2)
Radio_eelock= ttk.Radiobutton(page15,text='Reset React/EE',value=9)
Radio_eelock.grid(row=3,column=3)
Radio_download= ttk.Radiobutton(page15,text='Reboot to Download Mode',value=10)
Radio_download.grid(row=3,column=4)
Radio_frpufs= ttk.Radiobutton(page15,text='Reset Frp UFS',value=11)
Radio_frpufs.grid(row=3,column=5)
Radio_readcode = ttk.Radiobutton(page15,text='Read code',value=12)
Radio_readcode.grid(row=4,column=0)
Radio_frpadb = ttk.Radiobutton(page15,text='Reset Frp(DB)',value=13)
Radio_frpadb.grid(row=4,column=1)
Radio_root = ttk.Radiobutton(page15,text='Root (DB)',value=14)
Radio_root.grid(row=4,column=2)
Radio_efs = ttk.Radiobutton(page15,text='Restore efs',value=15)
Radio_efs.grid(row=4,column=3)
Radio_Recovery = ttk.Radiobutton(page15,text='Reboot to Recovery Mode',value=16)
Radio_Recovery.grid(row=4,column=4)
Radio_rmm = ttk.Radiobutton(page15,text='Fix RMM STATE',value=17)
Radio_rmm.grid(row=4,column=5)
Radio_diag = ttk.Radiobutton(page15,text='Enable Diag',value=18)
Radio_diag.grid(row=5,column=0)
Radio_DRK = ttk.Radiobutton(page15,text='Repair DRK',value=19)
Radio_DRK.grid(row=5,column=1)
Radsio_sprint = ttk.Radiobutton(page15,text='Sprint Unlock',value=20)
Radio_sprint.grid(row=5,column=2)
Radio_phonelock = ttk.Radiobutton(page15,text='Reset Phone lock',value=21)
Radio_phonelock.grid(row=5,column=3)
Radio_read_server = ttk.Radiobutton(page15,text='Read Code From Server',value=22)
Radio_read_server.grid(row=5,column=4)
Radio_factorymode = ttk.Radiobutton(page15,text='Fix Factory Mode',value=23)
Radio_factorymode.grid(row=5,column=5)

btn= ttk.Button(main,text='Start Button',width=30)
btn.grid(sticky='sw')
btn2= ttk.Button(main,text='Stop Button',width=30)
btn2.grid(sticky='sw')

def serial_ports():    
    return serial.tools.list_ports.comports()

def on_select(event=None):

    # get selection from event    
    print("event.widget:", event.widget.get())

    # or get selection directly from combobox
    print("comboboxes: ", cb.get())


cb = ttk.Combobox(main,width=45, values=serial_ports())
cb.grid(sticky='sw')

# assign function to combobox
cb.bind('<<ComboboxSelected>>', on_select)

def update_serial_list(event=None):
       ports = list(serial.tools.list_ports.comports())
       for p in ports:
          print(p)
          

refresh = ttk.Button(main,text='scan',width=5,command=update_serial_list)
refresh.grid(sticky='Sw')

pb_bar = ttk.Progressbar(main,orient="horizontal", length=780, mode="determinate")
pb_bar.grid()
pb_bar.start()

label2 = ttk.Label(main)
label2.grid(sticky='sw')

page16 = ttk.Frame(nb)
nb.add(page16, text='About Software')
about_software= ttk.Label(page16,text='This Programm is coded by Mamour Ndiaye,All Rights Reserved Version 2018-2019, Please buy Software from \n Authorised Mamour Ndiaye Partners.If you dont buy it from Authorised Reseller buy at your own risk',font=16)
about_software.grid()

def reset_frp():
    pass

def fix_rmm_state():
    pass

def reset_frp_mtk():
    pass

def enable_diag():
    pass

def write_flash():
    pass

def reboot_download_mode():
    pass

def repair_drk():
    pass

def sprint_unlock():
    pass

def repair_imei():
    pass
main.mainloop()
